// AUTO-GENERATED from MySQL table "refreshToken" at 2026-05-20T22:06:50.958Z.
// Do not edit this file directly. Regenerate it with:
// npm run generate:resource -- refreshToken --from-db

import { RowDataPacket } from "mysql2";

export interface RefreshTokenDTO extends RowDataPacket {
  refreshTokenId: number;
  userId: number;
  tokenHash: string;
  isRevoked: number;
  inserted: string | null;
  updated: string | null;
  expiration: string;
}
