// AUTO-GENERATED from MySQL table "user" at 2026-05-20T22:19:44.383Z.
// Do not edit this file directly. Regenerate it with:
// npm run generate:resource -- user --from-db

import { RowDataPacket } from "mysql2";

export interface UserDTO extends RowDataPacket {
  userId: number;
  email: string;
  password: string;
  inserted: string | null;
  updated: string | null;
}
