CREATE TABLE IF NOT EXISTS user (
  userId INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  inserted TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS refreshToken (
  refreshTokenId INT AUTO_INCREMENT PRIMARY KEY,
  userId INTEGER NOT NULL REFERENCES user(userId) ON DELETE CASCADE,
  tokenHash varchar(64) not null, 
  isRevoked TINYINT NOT NULL DEFAULT 0,
  expiration TIMESTAMP,
  inserted TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
